import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import test from "node:test";

test("Concepts surface renders saved concepts as an expandable tree", () => {
  const source = readFileSync(fileURLToPath(new URL("./KnowledgeBaseSurface.tsx", import.meta.url)), "utf8");
  const css = readFileSync(fileURLToPath(new URL("../../index.css", import.meta.url)), "utf8");

  assert.match(source, /aria-label="Concept tree"/);
  assert.match(source, /ConceptTreeListNode/);
  assert.match(source, /buildConceptRecordTree/);
  assert.match(source, /collapsedTreePaths/);
  assert.match(source, /conceptTreePath/);
  assert.match(source, /conceptSegmentLabel/);
  assert.match(source, /ConceptTreeGroupRow/);
  assert.match(source, /ml-\[1\.125rem\] border-l/);
  assert.match(source, /construct-concept-tree-accordion__content/);
  assert.match(source, /RecordDetails/);
  assert.match(source, /onNodeHover/);
  assert.match(source, /graphRecordConnections/);
  assert.match(source, /GraphMetric/);
  assert.match(source, /graphRef/);
  assert.match(source, /focusGraphCameraOnNode/);
  assert.match(source, /graphCameraApproachDirection/);
  assert.match(source, /graphCameraOrbitAngleDelta/);
  assert.match(source, /normalizeGraphCameraAngle/);
  assert.match(source, /graphCameraFocusFrame/);
  assert.match(source, /cameraPosition/);
  assert.match(source, /requestAnimationFrame/);
  assert.match(source, /selectedPulse/);
  assert.match(source, /graphNodeColor/);
  assert.match(source, /graphNodeValue/);
  assert.match(source, /graphLinkTouchesSelected/);
  assert.match(source, /orbitGraphCameraAroundNode/);
  assert.match(source, /createGraphCameraOrbitState/);
  assert.match(source, /initialAngle/);
  assert.match(source, /graphCameraFocusDistance/);
  assert.match(source, /#ff1744/);
  assert.doesNotMatch(source, /buildKnowledgeGraph\(records, selectedKey\)/);
  assert.doesNotMatch(source, /from "three"/);
  assert.doesNotMatch(source, /KnowledgeVisualMode/);
  assert.doesNotMatch(source, /construct-sci-fi/);
  assert.doesNotMatch(css, /construct-sci-fi/);
  assert.match(css, /\.construct-concept-tree-accordion__content/);
  assert.match(css, /grid-template-rows 280ms cubic-bezier/);
  assert.doesNotMatch(source, /<ConceptSection title="Summary">/);
  assert.doesNotMatch(source, /record\.content \|\| record\.summary/);
  assert.doesNotMatch(source, /aria-label="Concept cards"/);
  assert.doesNotMatch(source, /group rounded-\[8px\] border bg-background\/70/);
  assert.doesNotMatch(source, /ConceptStat/);
  assert.doesNotMatch(source, /HistoryEventDetails/);
});
