import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import test from "node:test";

test("Concepts surface renders saved concepts as an expandable tree", () => {
  const source = readFileSync(fileURLToPath(new URL("./KnowledgeBaseSurface.tsx", import.meta.url)), "utf8");
  const fileTreeSource = readFileSync(fileURLToPath(new URL("./FileTree.tsx", import.meta.url)), "utf8");
  const fileIconSource = readFileSync(fileURLToPath(new URL("./workspace/fileIcons.tsx", import.meta.url)), "utf8");
  const typesSource = readFileSync(fileURLToPath(new URL("../types.ts", import.meta.url)), "utf8");
  const opalineFileTreeSource = readFileSync(fileURLToPath(new URL("../../../../../opaline/packages/ui/src/file-tree/FileTree.tsx", import.meta.url)), "utf8");
  const css = readFileSync(fileURLToPath(new URL("../../index.css", import.meta.url)), "utf8");

  assert.match(source, /OpalineFileTree/);
  assert.match(source, /conceptTreeNodeToFileTreeItem/);
  assert.match(source, /ConceptColorIcon/);
  assert.match(source, /ConceptGroupDetail/);
  assert.match(source, /Child Concepts/);
  assert.match(source, /collectConceptRecords/);
  assert.match(source, /findConceptTreeNodeByPath/);
  assert.match(source, /placeholder="Search concepts\.\.\."/);
  assert.match(source, /record\.parentId/);
  assert.match(source, /findParentRecord/);
  assert.match(source, /attachSyntheticPath/);
  assert.match(source, /conceptRecordTreePath/);
  assert.match(source, /buildConceptRecordTree/);
  assert.match(source, /expandedTreePaths/);
  assert.match(source, /isConceptTreeContainerNode\(selectedTreeNode\)/);
  assert.match(source, /selectedConceptRecord/);
  assert.match(source, /headerTitle/);
  assert.match(source, /headerDetail/);
  assert.match(source, /conceptTreePath/);
  assert.match(source, /conceptSegmentLabel/);
  assert.match(source, /RecordDetails/);
  assert.match(source, /onNodeHover/);
  assert.match(source, /graphRecordConnections/);
  assert.match(source, /GraphMetric/);
  assert.match(source, /aria-expanded=\{expanded\}/);
  assert.match(source, /onSidebarPanelChange/);
  assert.match(source, /ConceptsSidebarPanel/);
  assert.match(source, /graphPaneWidth/);
  assert.match(source, /startGraphResize/);
  assert.match(source, /Resize knowledge web/);
  assert.match(source, /graphRef/);
  assert.match(source, /focusGraphCameraOnNode/);
  assert.match(source, /GraphCameraFlight/);
  assert.match(source, /graphCameraFlightEase/);
  assert.match(source, /interpolateNumber/);
  assert.match(source, /graphCameraApproachDirection/);
  assert.match(source, /graphCameraOrbitAngleDelta/);
  assert.match(source, /normalizeGraphCameraAngle/);
  assert.match(source, /graphCameraFocusFrame/);
  assert.match(source, /cameraPosition/);
  assert.match(source, /requestAnimationFrame/);
  assert.match(source, /selectedPulse/);
  assert.match(source, /graphNodeColor/);
  assert.match(source, /graphNodeValue/);
  assert.match(source, /graphLinkTouchesSelected/);
  assert.match(source, /orbitGraphCameraAroundNode/);
  assert.match(source, /createGraphCameraOrbitState/);
  assert.match(source, /initialAngle/);
  assert.match(source, /graphCameraFocusDistance/);
  assert.match(source, /onBackgroundClick=\{clearGraphSelection\}/);
  assert.match(source, /onLinkClick=\{clearGraphSelection\}/);
  assert.match(source, /clearGraphSelection/);
  assert.match(source, /cameraFlightCancelRef/);
  assert.match(source, /setHoveredKey\(null\)/);
  assert.match(source, /setSelectedKey\(null\)/);
  assert.match(source, /#ff1744/);
  assert.match(source, /graphGroupForRecord/);
  assert.match(source, /ConceptGroupIcon/);
  assert.match(source, /hideChevron: isConceptRecord/);
  assert.match(source, /children: hasChildren \?/);
  assert.match(source, /isParentConceptStub/);
  assert.match(fileTreeSource, /placeholder="Search files\.\.\."/);
  assert.match(opalineFileTreeSource, /gridTemplateRows: isExpanded \? "1fr" : "0fr"/);
  assert.match(opalineFileTreeSource, /pointerEvents: isExpanded \? undefined : "none"/);
  assert.match(opalineFileTreeSource, /grid-template-rows 240ms cubic-bezier/);
  assert.doesNotMatch(source, /circle at 46% 42%/);
  assert.match(source, /nodeResolution=\{18\}/);
  assert.doesNotMatch(fileTreeSource, /searchPlaceholder/);
  assert.doesNotMatch(fileTreeSource, /onSearchQueryChange/);
  assert.doesNotMatch(fileTreeSource, /node\.iconColor/);
  assert.doesNotMatch(fileIconSource, /color\?: string/);
  assert.doesNotMatch(fileIconSource, /options\.color/);
  assert.doesNotMatch(typesSource, /iconColor/);
  assert.doesNotMatch(source, /if \(!selectedKey \|\| !filtered\.some/);
  assert.doesNotMatch(source, /buildKnowledgeGraph\(records, selectedKey\)/);
  assert.doesNotMatch(source, /from "three"/);
  assert.doesNotMatch(source, /KnowledgeVisualMode/);
  assert.doesNotMatch(source, /construct-sci-fi/);
  assert.doesNotMatch(css, /construct-sci-fi/);
  assert.doesNotMatch(source, /<FileTree/);
  assert.doesNotMatch(source, /ConceptTreeNodeRow/);
  assert.doesNotMatch(source, /construct-concept-tree-accordion__content/);
  assert.doesNotMatch(source, /<h2 className="truncate text-lg/);
  assert.doesNotMatch(source, /<p className="mt-1 truncate font-mono/);
  assert.doesNotMatch(source, /\?\? records\[0\]/);
  assert.doesNotMatch(source, /conceptTreeRecordNodeToWorkspaceNode/);
  assert.doesNotMatch(source, /ConceptListCard/);
  assert.doesNotMatch(source, /<ConceptSection title="Summary">/);
  assert.doesNotMatch(source, /<ConceptSection title="Overview">/);
  assert.doesNotMatch(source, />\s*Concept detail\s*</);
  assert.doesNotMatch(source, />\s*Open project\s*</);
  assert.doesNotMatch(source, /record\.content \|\| record\.summary/);
  assert.doesNotMatch(source, /aria-label="Concept cards"/);
  assert.doesNotMatch(source, /group rounded-\[8px\] border bg-background\/70/);
  assert.doesNotMatch(source, /ConceptStat/);
  assert.doesNotMatch(source, /HistoryEventDetails/);
});
