import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import test from "node:test";

test("Concepts surface renders saved concepts as an expandable tree", () => {
  const source = readFileSync(fileURLToPath(new URL("./KnowledgeBaseSurface.tsx", import.meta.url)), "utf8");
  const fileTreeSource = readFileSync(fileURLToPath(new URL("./FileTree.tsx", import.meta.url)), "utf8");
  const fileIconSource = readFileSync(fileURLToPath(new URL("./workspace/fileIcons.tsx", import.meta.url)), "utf8");
  const typesSource = readFileSync(fileURLToPath(new URL("../types.ts", import.meta.url)), "utf8");
  const opalineFileTreeSource = readFileSync(fileURLToPath(new URL("../../../../../opaline/packages/ui/src/file-tree/FileTree.tsx", import.meta.url)), "utf8");
  const css = readFileSync(fileURLToPath(new URL("../../index.css", import.meta.url)), "utf8");

  assert.match(source, /OpalineFileTree/);
  assert.match(source, /conceptTreeNodeToFileTreeItem/);
  assert.match(source, /ConceptColorIcon/);
  assert.match(source, /ConceptGroupDetail/);
  assert.match(source, /Child Concepts/);
  assert.match(source, /collectConceptRecords/);
  assert.match(source, /findConceptTreeNodeByPath/);
  assert.match(source, /placeholder="Search concepts\.\.\."/);
  assert.match(source, /record\.parentId/);
  assert.match(source, /findParentRecord/);
  assert.match(source, /attachSyntheticPath/);
  assert.match(source, /conceptRecordTreePath/);
  assert.match(source, /buildConceptRecordTree/);
  assert.match(source, /expandedTreePaths/);
  assert.match(source, /isConceptTreeContainerNode\(selectedTreeNode\)/);
  assert.match(source, /selectedConceptRecord/);
  assert.match(source, /headerTitle/);
  assert.match(source, /headerDetail/);
  assert.match(source, /conceptTreePath/);
  assert.match(source, /conceptSegmentLabel/);
  assert.match(source, /RecordDetails/);
  assert.match(source, /onNodeHover/);
  assert.match(source, /graphRecordConnections/);
  assert.match(source, /GraphMetric/);
  assert.match(source, /aria-expanded=\{expanded\}/);
  assert.match(source, /onSidebarPanelChange/);
  assert.match(source, /ConceptsSidebarPanel/);
  assert.match(source, /graphPaneWidth/);
  assert.match(source, /startGraphResize/);
  assert.match(source, /Resize knowledge web/);
  assert.match(source, /graphRef/);
  assert.match(source, /graphCanMount/);
  assert.match(source, /ConstructAuthLogo/);
  assert.match(source, /construct-auth-logo__mark--knowledge-web-loading/);
  assert.match(source, /const graphWidth = size\.width/);
  assert.match(source, /const graphHeight = size\.height/);
  assert.match(source, /const graphCanMount = graphWidth > 0 && graphHeight > 0/);
  assert.match(source, /graphCanMount \? \(/);
  assert.match(source, /width=\{graphWidth\}/);
  assert.match(source, /height=\{graphHeight\}/);
  assert.match(source, /import ForceGraph3D, \{ type ForceGraphMethods/);
  assert.match(source, /getBoundingClientRect/);
  assert.match(source, /requestAnimationFrame\(measureElementSize\)/);
  assert.match(source, /window\.addEventListener\("resize", scheduleMeasure\)/);
  assert.match(source, /focusGraphCameraOnNode/);
  assert.match(source, /GraphCameraFlight/);
  assert.match(source, /useState<string \| null>\(null\)/);
  assert.match(source, /KNOWLEDGE_GRAPH_LINK_DISTANCE/);
  assert.match(source, /KNOWLEDGE_GRAPH_CHARGE_STRENGTH/);
  assert.match(source, /KNOWLEDGE_GRAPH_CENTER_STRENGTH/);
  assert.match(source, /linkForce\?\.distance\?\.\(KNOWLEDGE_GRAPH_LINK_DISTANCE\)/);
  assert.match(source, /chargeForce\?\.strength\?\.\(KNOWLEDGE_GRAPH_CHARGE_STRENGTH\)/);
  assert.match(source, /centerForce\?\.strength\?\.\(KNOWLEDGE_GRAPH_CENTER_STRENGTH\)/);
  assert.match(source, /d3ReheatSimulation/);
  assert.match(source, /zoomToFit\?\.\(650, 80\)/);
  assert.match(source, /cooldownTicks=\{160\}/);
  assert.match(source, /cooldownTime=\{15000\}/);
  assert.match(source, /d3AlphaDecay=\{0\.016\}/);
  assert.match(source, /d3VelocityDecay=\{0\.24\}/);
  assert.match(source, /graphCameraFlightEase/);
  assert.match(source, /interpolateNumber/);
  assert.match(source, /graphCameraApproachDirection/);
  assert.match(source, /graphCameraOrbitAngleDelta/);
  assert.match(source, /normalizeGraphCameraAngle/);
  assert.match(source, /graphCameraFocusFrame/);
  assert.match(source, /cameraPosition/);
  assert.doesNotMatch(source, /setGraphReady/);
  assert.doesNotMatch(source, /onEngineTick=\{\(\) => setGraphReady\(true\)\}/);
  assert.doesNotMatch(source, /onEngineStop=\{\(\) => setGraphReady\(true\)\}/);
  assert.match(source, /requestAnimationFrame/);
  assert.match(source, /selectedPulse/);
  assert.match(source, /graphNodeColor/);
  assert.match(source, /graphNodeValue/);
  assert.match(source, /graphLinkTouchesSelected/);
  assert.match(source, /orbitGraphCameraAroundNode/);
  assert.match(source, /createGraphCameraOrbitState/);
  assert.match(source, /initialAngle/);
  assert.match(source, /graphCameraFocusDistance/);
  assert.match(source, /onBackgroundClick=\{clearGraphSelection\}/);
  assert.match(source, /onLinkClick=\{clearGraphSelection\}/);
  assert.match(source, /clearGraphSelection/);
  assert.match(source, /cameraFlightCancelRef/);
  assert.match(source, /setHoveredKey\(null\)/);
  assert.match(source, /setSelectedKey\(null\)/);
  assert.match(source, /#ff1744/);
  assert.match(source, /graphGroupForRecord/);
  assert.match(source, /ConceptGroupIcon/);
  assert.match(source, /hideChevron: isConceptRecord/);
  assert.match(source, /children: hasChildren \?/);
  assert.match(source, /isParentConceptStub/);
  assert.match(css, /\.construct-auth-logo__mark--knowledge-web-loading\s*\{/);
  assert.match(css, /animation: opaline-agent-thinking-shimmer 1\.25s linear infinite/);
  assert.match(fileTreeSource, /placeholder="Search files\.\.\."/);
  assert.match(opalineFileTreeSource, /gridTemplateRows: isExpanded \? "1fr" : "0fr"/);
  assert.match(opalineFileTreeSource, /pointerEvents: isExpanded \? undefined : "none"/);
  assert.match(opalineFileTreeSource, /grid-template-rows 240ms cubic-bezier/);
  assert.doesNotMatch(source, /circle at 46% 42%/);
  assert.doesNotMatch(source, /Loading knowledge web/);
  assert.doesNotMatch(source, /radial-gradient/);
  assert.match(source, /nodeResolution=\{18\}/);
  assert.doesNotMatch(fileTreeSource, /searchPlaceholder/);
  assert.doesNotMatch(fileTreeSource, /onSearchQueryChange/);
  assert.doesNotMatch(fileTreeSource, /node\.iconColor/);
  assert.doesNotMatch(fileIconSource, /color\?: string/);
  assert.doesNotMatch(fileIconSource, /options\.color/);
  assert.doesNotMatch(typesSource, /iconColor/);
  assert.doesNotMatch(source, /if \(!selectedKey \|\| !filtered\.some/);
  assert.doesNotMatch(source, /buildKnowledgeGraph\(records, selectedKey\)/);
  assert.doesNotMatch(source, /Math\.max\(1, Math\.floor\(entry\.contentRect\.(width|height)\)\)/);
  assert.doesNotMatch(source, /records\[0\] \? recordKey\(records\[0\]\)/);
  assert.doesNotMatch(source, /records\[0\] \? conceptRecordTreePath\(records\[0\]\)/);
  assert.doesNotMatch(source, /GraphNodeWave/);
  assert.doesNotMatch(source, /triggerGraphWave/);
  assert.doesNotMatch(source, /applyGraphNodeWave/);
  assert.doesNotMatch(source, /graphNodeWaveAmount/);
  assert.doesNotMatch(source, /createKnowledgeGraphWaveForce/);
  assert.doesNotMatch(source, /knowledge-wave/);
  assert.doesNotMatch(source, /KNOWLEDGE_GRAPH_WAVE/);
  assert.doesNotMatch(source, /runtimeNode\.vx/);
  assert.doesNotMatch(source, /runtimeNode\.vy/);
  assert.doesNotMatch(source, /runtimeNode\.vz/);
  assert.doesNotMatch(source, /cooldownTicks=\{Infinity\}/);
  assert.doesNotMatch(source, /cooldownTime=\{Infinity\}/);
  assert.doesNotMatch(source, /graphFloatAnchorsRef/);
  assert.doesNotMatch(source, /graphNodeFloatPhase/);
  assert.doesNotMatch(source, /createKnowledgeGraphFloatForce/);
  assert.doesNotMatch(source, /knowledge-float/);
  assert.doesNotMatch(source, /KNOWLEDGE_GRAPH_FLOAT_STRENGTH = 0\.432/);
  assert.doesNotMatch(source, /lastReheatAt > 2500/);
  assert.doesNotMatch(source, /runtimeNode\.x = anchor\.x/);
  assert.doesNotMatch(source, /runtimeNode\.y = anchor\.y/);
  assert.doesNotMatch(source, /runtimeNode\.z = anchor\.z/);
  assert.doesNotMatch(source, /lazy\(\(\) => import\("react-force-graph-3d"\)\)/);
  assert.doesNotMatch(source, /<Suspense fallback=\{<GraphLoadingState \/>}/);
  assert.doesNotMatch(source, /from "three"/);
  assert.doesNotMatch(source, /KnowledgeVisualMode/);
  assert.doesNotMatch(source, /construct-sci-fi/);
  assert.doesNotMatch(css, /construct-sci-fi/);
  assert.doesNotMatch(source, /<FileTree/);
  assert.doesNotMatch(source, /ConceptTreeNodeRow/);
  assert.doesNotMatch(source, /construct-concept-tree-accordion__content/);
  assert.doesNotMatch(source, /<h2 className="truncate text-lg/);
  assert.doesNotMatch(source, /<p className="mt-1 truncate font-mono/);
  assert.doesNotMatch(source, /\?\? records\[0\]/);
  assert.doesNotMatch(source, /conceptTreeRecordNodeToWorkspaceNode/);
  assert.doesNotMatch(source, /ConceptListCard/);
  assert.doesNotMatch(source, /<ConceptSection title="Summary">/);
  assert.doesNotMatch(source, /<ConceptSection title="Overview">/);
  assert.doesNotMatch(source, />\s*Concept detail\s*</);
  assert.doesNotMatch(source, />\s*Open project\s*</);
  assert.doesNotMatch(source, /record\.content \|\| record\.summary/);
  assert.doesNotMatch(source, /aria-label="Concept cards"/);
  assert.doesNotMatch(source, /group rounded-\[8px\] border bg-background\/70/);
  assert.doesNotMatch(source, /ConceptStat/);
  assert.doesNotMatch(source, /HistoryEventDetails/);
});
